SET SERVEROUTPUT ON;
DECLARE
    NOTA NUMBER := 89;
BEGIN
    IF NOTA >= 90 THEN
        DBMS_OUTPUT.PUT_LINE('NOTA A');
    ELSIF NOTA >= 80 AND NOTA < 90 THEN
        DBMS_OUTPUT.PUT_LINE('NOTA B');
    ELSIF NOTA >= 70 AND NOTA < 80 THEN
        DBMS_OUTPUT.PUT_LINE('NOTA C');
    ELSIF NOTA >= 60 AND NOTA < 79 THEN
        DBMS_OUTPUT.PUT_LINE('NOTA D');
    ELSE
        DBMS_OUTPUT.PUT_LINE('NOTA F');
END IF;
END;