SET SERVEROUTPUT ON;
DECLARE
    VALOR_CARRO NUMBER := &VALOR_DO_CARRO;
    PARCELAS_6 NUMBER;
    PARCELAS_12 NUMBER;
    PARCELAS_18 NUMBER;
BEGIN
    VALOR_CARRO:= VALOR_CARRO-VALOR_CARRO*0.20;
    DBMS_OUTPUT.PUT_LINE('VALOR A SER FINANCIADO R$ '||VALOR_CARRO);
    PARCELAS_6:= VALOR_CARRO*1.10;
    DBMS_OUTPUT.PUT_LINE('VALOR TOTAL DAS PARCELAS 6X R$ '||PARCELAS_6);
    PARCELAS_12:= VALOR_CARRO*1.15;
    DBMS_OUTPUT.PUT_LINE('VALOR TOTAL DAS PARCELAS 12X R$ '||PARCELAS_12);
    PARCELAS_18:= VALOR_CARRO*1.20;
    DBMS_OUTPUT.PUT_LINE('VALOR TOTAL DAS PARCELAS 18X R$ '||PARCELAS_18);
END;